### ISSUE TITLE
スタミ日程調整

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#10]
@ES-mabou 
制作の仕事として、まず始めにチーフチャンネルでスタミの日程調整します！
ちょっと今回スレッドは私が投げちゃったんですが、卒公からはお任せします🙇
 回答期限は8/26までにしてます！

**Comment by ES-mabou** [comment]
@ES-hasuke 
わかりました！
この日程調整は私も回答するべきでしょうか

**Comment by ES-hasuke** [comment]
@ES-mabou 
ありがとう〜🙏
そうだね、スタミの進行をそのうち任せられるといいなあ、と思ってるから、回答お願いします🙇

**Comment by ES-mabou** [comment]
了解です！

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/0bc317a1-8d0c-48b6-8c82-977eaf7d1e90)
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/3af2e205-9d1b-4759-a444-c7c99dae560c)
@ES-mabou 
締め切り前ではあるんだけど、チーフチャンネルにいる人全員の回答出揃ったっぽいから共有しとくね〜！
多分、金曜21:30〜が1番いいかも！
ちょっと金曜行けないっぽいチーフさんもいるんだけど、そこに関しては代理を立ててもらうのがいいかなあという感じ！

**Comment by ES-hasuke** [comment]
@ES-mabou 
がちで何回もごめん🙏
第0回スタミ、進行どっちがやる…？
「最初からやります！」って感じだったらお任せしちゃうし(もちろん、話したいこと、聞いてほしいことは共有しとくね)
もし不安だったら、そうほうさいの最初の方は進行うちがやって、後半(10月に入ってからとかかな)お任せする感じでもいいかなあと思ってる…！

**Comment by ES-mabou** [comment]
@ES-hasuke 
雙峰祭のスタミについて、初めのうちは進行をお任せしてよろしいでしょうか。
スタミの進行にまだ不安があり、実践の前に改めて進行の仕方を確認するべきだと思いました。
できるだけ早く仕事を覚えて交代できるように‪します。
