### ISSUE TITLE
8/9 機材借り

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#103]
今回の機材借りについて、 大学側の一斉休業の関係で生活課の機材を借りられるのが8/9までになりそうなので、生活課と実委の機材は8/9に借りて、筑小とノイの機材は仕込みの初日に借りる形にすることになりました！
そこで機材借りの出欠調査について舞監と話し合った結果、機材返しみたいに仕込みとは別で制作が個別で行うことになったので、急遽フォームを作りました！↓

8/9 機材借り出欠調査

https://docs.google.com/forms/d/e/1FAIpQLSdMdNLrVmHwhOal3GiBZsUhn7SO8ksPj6C5OJcmamHGqfiH2A/viewform?usp=sf_link

確認お願いします🙏
回答締切は8/7にするつもりです！
あと、Slackのリアクションでアンケートを取るよりフォームの方がしっかりしていてみんな当事者としての自覚が出ると思うので、機材返しもフォームで出欠調査取ろうかなと思ってます！

**Comment by ES-mabou** [comment]
@ES-Itoshima @ESkoi-koi @ES-hasuke @ES-Mocchi 
特に問題がなさそうであれば、このまま流しちゃいます！

**Comment by ES-Mocchi** [comment]
![IMG_0039](https://github.com/user-attachments/assets/a2916d72-60f6-417e-b53e-41997aa05636)

実委さんから了承のお返事いただきました！

**Comment by ES-mabou** [comment]
8/20の機材借りの出欠調査フォームを作ったので、確認お願いします！
集合は10:55にカンシタ集合にするつもりです

https://docs.google.com/forms/d/e/1FAIpQLSf0jLsiwDFf9MzeQ_JBSLVVXF6keo821lN-HSi1_WgzbMMRVA/viewform?usp=sf_link
