### ISSUE TITLE
夏休み教室予約連絡用

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#106]
雙峰祭教室予約のissueが結構中身が多くなっちゃったので、誰がいつ予約に行くかなどの調整の連絡はこちらをメインにしようと思います。

改めて、夏休み中の教室予約の担当は
-8/23: @ES-mabou @ESkoi-koi @ES-Mocchi 
8/26-31: @ESkoi-koi @ES-Mocchi 
9/2-6: @ESkoi-koi
9/9-9/30: @ES-mabou @ES-Mocchi 
でお願いします！
特に土日祝は5C508,616,617,618を確保できるようにしてください！

**Comment by ES-mabou** [comment]
~9/21,22,23が土日祝なので、その予約をしたいです！
明日は私が行けるので21,22分を予約しようと思うのですが、23は午前中予定があるので、 @ESkoi-koi @ES-Mocchi どちらか予約に行って貰えないでしょうか？~
明日9/21,22分の予約いってきます！

**Comment by ES-mabou** [comment]
↑そういえば9/23って月曜日だからえっさ休息日ですやん
聞かなかったことにしてください

**Comment by ES-mabou** [comment]
@ES-Mocchi 
来週から基本的に2人で教室予約に行くことになるとおもうんだけど、もっちーは何曜日なら都合がいいとかある？

**Comment by ES-Mocchi** [comment]
@ES-mabou 
基本的には午前中なら何曜日でも大丈夫です！
ただいまのところ以下の日は午前中から用事あり厳しいです...
9/9,10,11,26,27

**Comment by ES-mabou** [comment]
じゃあ来週はとりあえず私が9/10に予約に行くので、9/13に予約に行ってもらってもいい？

**Comment by ES-Mocchi** [comment]
了解です！
ありがとうございます🙇‍♀️

**Comment by ES-mabou** [comment]
@ES-Mocchi 
今週の教室予約も、俺が火曜日に行くのでもっちーは金曜日に行ってもらってもいい？

**Comment by ES-Mocchi** [comment]
オッケーです！お願いします

**Comment by ES-mabou** [comment]
@ES-Mocchi 
もっちーは今週の教室予約いつなら空いてる？

**Comment by ES-Mocchi** [comment]
27金の予定がなくなったので、26木以外なら行けます！

**Comment by ES-mabou** [comment]
おけ
じゃあ明日行ってもらってもいい？

**Comment by ES-Mocchi** [comment]
了解です！
