### ISSUE TITLE
トラック

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#111]
トラック予約した??

あと月曜日に移動するならそれも込みで取った方がいいよ多分

**Comment by ES-mabou** [comment]
トラックの予約まだだったと思います…！
卒公のトラックレンタルの担当が少なくとも年内は @ES-Itoshima というふうになっていたと思うので、お願いしてもいいでしょうか？

@ES-Mocchi  
トラックのレンタルの時間がまだ分かっていないと思うので、どのくらいの間トラックを使いたいか舞監に確認取って欲しいです！

それと、お仕事chでも言った通りパイプとかコの字とかは24のうちに運び込んで、かつ25は最低限借用してる機材だけを運んでえっさ所有の機材は一旦春日に置いておいてもいいのかなぁと思ってるのですが、それなら自家用車だけでも何とかなったりしませんかね…？

えっさの機材は次の通し後とかの人が沢山確保できる時にカンシタに戻すのでどうか、と思ってます

**Comment by ES-Itoshima** [comment]
おけわかった

あとかんした通路の使用許可出しといて欲しい

**Comment by ES-Itoshima** [comment]
おけわかった

あとかんした通路の使用許可出しといて欲しい

**Comment by ES-mabou** [comment]
@ES-Itoshima 
どうも11/23,24の立ち入り禁止の要因だったシンポジウムが中止になった＆舞監が引き継ぎ建て込みを23までに収まるように調整してくれたので、普段通りの運搬ができるようになりました！

@ES-Mocchi 
カンシタ活動団体のグループLINEで、11/22,23で運搬をするからカンシタ通路を使う旨の連絡をお願いします！
運搬の時間帯は仕込み帳を目安にしてください

**Comment by ES-Mocchi** [comment]
承知しました！
舞監さんに連絡したので返答あり次第対応します

**Comment by ES-Mocchi** [comment]
@channel
トラックの借用したい時間について返答いただきました。
11/23金：17:15~20:30

11/24土：17:20~21:15

とのことなのでよろしくお願いします！

**Comment by ES-mabou** [comment]
たぶん
11/22(金):17:15-20:30
11/23(土):17:20-21:15
かな？

**Comment by ES-Mocchi** [comment]
そうです！すみません、一日ずれてましたがマー坊さんの書いてくれたのが正しいです

**Comment by ES-Itoshima** [comment]
了解取っといた
