### ISSUE TITLE
予約する教室について

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#12]
雙峰祭での予約教室はしていないらしいので基本７A、通しのみ５Cとしましょう

**Comment by ES-hasuke** [comment]
冷房がつかないってことで合ってますかね？
了解しました！

**Comment by ES-mabou** [comment]
@ES-Itoshima
先ほど演出さんから、今後の練習教室は既に教室をとってある9月分を含めて7Aで行いたいという旨の連絡が制作チャンネルでありましたが、これは今予約されている教室に加えて7Aの教室も予約もしておくということでいいのでしょうか。
そうであれば、明日明後日辺りに今教室予約されている日時分の7Aの予約を取りに行こうと思うのですが

**Comment by ES-hasuke** [comment]
@ES-mabou 
横から失礼！全然返信できてなくてすまん…！！Slackも気づいてなかった…！
そうね、多分なる早で対処したほうがいいやつだから、行けそうなら明日お願いしてもいい？
5日後より直近のやつは多分無理だから、来週以降の分くらいになるかな、と思います！

**Comment by ES-mabou** [comment]
了解です！

**Comment by ES-mabou** [comment]
@ES-hasuke 
9/21~30は学会があって教室取れませんでした

**Comment by ES-hasuke** [comment]
教室予約ありがと！！めっちゃ助かる🙏
うーん、わろしだね〜(大学に対する悪口)
明日うち教室予約行けるから、5Cとか取っちゃうね！
冷房問題はもう…夏休み中は個人でなんとか気をつけて暑さ対策してもらうしかないかなあ…授業時間外だと冷房つかないなら…
