### ISSUE TITLE
臨時教室予約

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#13]
演出が本番教室をチェックしたいらしいので8/29　9:00-21:00で5C616の予約をお願いします。

**Comment by ES-hasuke** [comment]
多分皆さん帰省中だと思うんで私見てきますね〜
もし29がダメそうなら、練習開始前の他の日を提案してみます…！

**Comment by ES-hasuke** [comment]
8/29無理だったので、
8/31 9:00〜21:00で予約しました！
