### ISSUE TITLE
制作引継ぎ用資料作成会

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#14]
8/24　16:00からzoomにて

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
あ、私が時間決めちゃったんですけど、教室予約の関係でちょっと遅れそうな予感がするので、16:30からとかでもいいですか？

**Comment by ES-Itoshima** [comment]
@ES-hasuke 
了解です

**Comment by ES-hasuke** [comment]
Zoomミーティングに参加する
https://us05web.zoom.us/j/7616918710?pwd=a1EwNU1IRkFTMHkyQythbDRMVitPdz09

ミーティングID: 761 691 8710
パスコード: 3xi18F



@ES-Itoshima こちらからお願いします！

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
資料できました！確認お願いします！
[制作チーフのお仕事マニュアル！](https://docs.google.com/document/d/1bm9OYfaIk2_RqsOpph3pFvwdvZazugdE9eH_Uuo5sVs/edit)
