### ISSUE TITLE
スケジュールの提出

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#17]
制作
9/6【制作】:スケジュール収集締め切り
9/14【制作】:関係者名簿作成締め切り
10/16〜10/22【制作】:反省会日程調整
11/6〜11/12【制作】:反省会

今回、本番教室予約とか機材の借用とかがなさそうなので、スケジュールはこんな感じになると思ってます！
確認お願いします！
@ES-mabou スケジュール提出やってみる？

**Comment by ES-mabou** [comment]
やります！

**Comment by ES-hasuke** [comment]
ありがとう〜！
チーフチャンネルのスレッドに提出お願いします🙇‍♀️
