### ISSUE TITLE
9/19の教室予約について

### ISSUE THREAD

**Issue by ESkoi-koi** [ES-Itoshima/ES_producer#18]
只今地元で車の免許を取るため教習所に通っているのですが、再検定の都合上9月18日までにつくば市に戻ることが難しいと判断しました。GitHubの試運転も兼ねての教室予約だったことを考えると申し訳ないのですが何方か代わりにお願いすることはできますか？

**Comment by ES-mabou** [comment]
@ESkoi-koi 
じゃあ俺代わりに行きますよ

**Comment by ES-hasuke** [comment]
めっちゃその日前撮りで、どこでもドアでもないと行けないから超助かります…！すまん！2人とも連絡ありがとう〜！
じゃあマー坊お願いします！ありがとう🙏

**Comment by ESkoi-koi** [comment]
わーーーマー坊ありがとう！！！
それじゃあ19日お願いします！
