### ISSUE TITLE
スケジュール作成

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#19]
[Googleカレンダー](https://calendar.google.com/calendar/u/0/embed?src=hsb8k2k1ccqof6m737n41n6ao4@group.calendar.google.com&ctz=Asia/Tokyo)
スケジュール、作成完了しました！確認お願いします！
@ES-mabou 卒公からは、多分この仕事もお任せすることになると思います！
大体、第一回スタミ(今回だったら今日)までに、集めたスケジュールをGoogleカレンダーに反映する感じ！

@ES-Itoshima 
あとすみません、今回chatGPTとエクセルを使ってやる方法ど忘れして、全部手入力で反映しました…！
1年ズに引き継ぎたいなあ…と思ってるので、どこかで直接教えるためのミーティングするor引き継ぎ資料作ってくださるととてもありがたいです…！

**Comment by ES-Itoshima** [comment]
了解です～MTの方が個人的にありがたいんだけどいつにしようか
@ES-hasuke

**Comment by ES-hasuke** [comment]
多分私以外にも、最低限マー坊はいたほうが良くないか？と思ってます…！
ちょっと個人的な都合ではあるのですが、
9/25〜10/1の間(9/30はえっさディズニーあるので除く)でもいいですか…？

**Comment by ES-mabou** [comment]
自分は今のところガチ練以外特に予定ないですし、大丈夫ですよ

**Comment by ES-Itoshima** [comment]
わたしもガチ練しかないです

**Comment by ES-Itoshima** [comment]
かんっぜんにわすれていたこれ
@ES-hasuke @ES-mabou 
今週の空き状況を教えてほしい！！

**Comment by ES-Itoshima** [comment]
できればあさってくらいがいいな！！

**Comment by ES-hasuke** [comment]
すみません、私もまじで忘れてました…
今週中ちょっと厳しいんですが、第4週で
9/25 〜12:00 15:00〜17:30
9/26 〜12:00 21:00〜
9/27 〜12:00 21:00〜
9/28 〜17:30 
9/29 〜12:00 15:00〜18:00
9/30 ❌
であれば空いてます…！

**Comment by ES-mabou** [comment]
9/22 -17:30
9/23 19:00-
9/24 19:00-
9/25 13:00-
9/26 -17:30,22:00-
9/27 -17:30,22:00-
9/28 -17:30,22:00-
9/29 -17:30,22:00-
こんな感じです

**Comment by ES-hasuke** [comment]
いとしま先輩さえ良ければ、9/26の22:00〜やっちゃうのが吉かもですが…いかがでしょう…？
@ES-Itoshima

**Comment by ES-Itoshima** [comment]
それでお願いします!!

**Comment by ES-hasuke** [comment]
@ES-Itoshima @ES-mabou 
めちゃくちゃ忘れてたんですがこれ今日でした！
zoom私が立てます！よろしくお願いします🙇

**Comment by ES-Itoshima** [comment]
ごめんなさい完全に明日と勘違いして武備の動き出し入れてました....

**Comment by ES-hasuke** [comment]
なるほど…おけです！
@ES-mabou 
明日にしたら行ける…？
もし無理そうだったら、卒公のスケジュール作るのを一緒にやっちゃう感じでもいいかなとは思う！

**Comment by ES-mabou** [comment]
自分は明日でも大丈夫ですよ

**Comment by ES-hasuke** [comment]
ありがとう…！
じゃあ明日の22:00〜でお願いします🙇

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
一応リマインドです！今日です！

**Comment by ES-hasuke** [comment]
zoomこちらです！

Zoom ミーティングに参加する
https://us05web.zoom.us/j/7616918710?pwd=a1EwNU1IRkFTMHkyQythbDRMVitPdz09

ミーティング ID： tel:7616918710
パスコード： 3xi18F

@ES-Itoshima @ES-mabou
