### ISSUE TITLE
事後報告・NEU借用書

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#20]
臨時で借用申請があったので通しました
以下の通りの借用書になります

武備には確認済みですすみません

**Comment by ES-Itoshima** [comment]
[ESSASSANEU_20230920-24_.pdf](https://github.com/ES-Itoshima/ES_producer/files/12674333/ESSASSANEU_20230920-24_.pdf)

**Comment by ES-hasuke** [comment]
ありがとうございます！資料がなぜかNot foundになっちゃうのはバグですかね…？
@ES-Itoshima

**Comment by ES-Itoshima** [comment]
アレなんでだろう私の環境だと見られるんだけどな

**Comment by ES-hasuke** [comment]
あれれえ〜おかしいぞお？(コナン)
携帯だと見られない的なアレかもしれないんで、まあなんとか確認してみます！
めちゃくちゃ帰省中だったんでご対応超助かります、ありがとうございます！🙏
