### ISSUE TITLE
卒公動き出しミ日程調整

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#21]
卒公の動き出しミをしたいです！
10/5～10/12の間で空いている日と時間帯を教えてくださいm(₋_₋)m
10/3までに回答していただけると嬉しいです！

**Comment by ES-hasuke** [comment]
ありがとう！よろしくお願いします🙇
10/5 ✖️
10/6 22:00〜
10/7 ✖️
10/8 18:00〜
10/9 ✖️
10/10 21:30〜
10/11 21:30〜
10/12 21:30〜
です！(ちょっと広報の引き継ぎ入ったから編集済み)

**Comment by ESkoi-koi** [comment]
11、12以外の日の夜だったらおそらくいつでも行けます！

**Comment by ES-mabou** [comment]
10/5 19:00-
10/6 12:00-17:30,22:00-
10/7 21:30-
10/8 いつでも
10/9 ‪✕‬
10/10 21:30-
10/11 12:30-17:30
10/12 ‪‪✕‬

**Comment by ES-Itoshima** [comment]
5 1500-
6 -16:30,1800-
7,8 -1800
9 -13:15,1800-
10 1800-
11 -11:00,1600-
12 1500-

**Comment by ES-mabou** [comment]
回答ありがとうございます！
そしたら10/6の22:00~が良さそうなのですが大丈夫でしょうか

**Comment by ES-mabou** [comment]
@ES-Itoshima @ES-hasuke @ESkoi-koi 
明日スタミ後の22:00から卒公動き出しミを行います！
出席お願いします🙇‍♀️

**Comment by ES-hasuke** [comment]
@ES-mabou 
議事録作っちゃった！よかったら使おう↓
[23卒せいさくぎじろく](https://docs.google.com/document/d/18DWB1pdlKPb5hBHvSiE5xvCT8wx1tGp0pFBwuHagX0E/edit)

**Comment by ES-mabou** [comment]
ありがとうございます！助かります！

**Comment by ES-mabou** [comment]
Zoom ミーティングに参加する
https://us05web.zoom.us/j/87495399662?pwd=eP2OfvWvqLOUdZj1GrO1C5cYsT1xZI.1

ミーティング ID： 874 9539 9662
パスコード： P0w6RG

動き出しミこちらからお願いします！
