### ISSUE TITLE
生活課 引き継ぎ建て込み 機材借用

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#23]
@ES-Itoshima 
早速なんですが、来週のどこかで生活課の機材予約行きたいです！
とりあえず平日5限までで私の空いてる時間投げときますね…！
9 5限
11 1〜3限、5限
12 1、2限と4限
13 1限、3、4限

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
あ、日程調整出しといてなんですけど、必要な機材さえわかれば行けるような気がしてきたので、明日の5限とかに行ってきますね
(追記)
全然行けてなくてわろた
今週中にはいきます

**Comment by ES-hasuke** [comment]
@ES-mabou 
金曜日に、生活課での借用は一通りやりました！報告遅れごめん！
@ES-Itoshima 
写真撮ってくださってたと思うので、卒公のドライブにアップロードお願いします！

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
今気づいたんですが、もしかしてこれ、いらない機材取り消しに行かないとでは？
私、明後日が全部空いてるんでどこかで行ってきますね

**Comment by ES-Itoshima** [comment]
だあああわすれてたごめん

**Comment by ES-Itoshima** [comment]
@ES-hasuke 今日わたしちょうど本学いるので行きます

**Comment by ES-hasuke** [comment]
神 あざす🙏
