### ISSUE TITLE
演出さんとの確認事項

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#24]
@ES-Itoshima @ES-hasuke 
この間の動き出しミで演出さんに聞くことになった
・オーディション期間の教室(5Cがおすすめ！)とオーディション教室について
・打ち上げのお店の希望について
のことで演出さんに確認が取れたので、内容を相談したくて立ち上げました！
まず、オーディション期間の教室は5Cで大丈夫そうです！
打ち上げの場所はお酒が飲めるところで、ここ数年で行けてない場所がいいかもってことでした。例年の打ち上げはどこに行ってたとか分かりますかね？

以下演出さんからの返信です
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915132/c0249ce9-0e80-44f0-859c-debc0429da2d)

**Comment by ES-hasuke** [comment]
最強にしごはや ありがとう🙏
打ち上げは、うちが入ってからは大体百香かえんやしか経験してないから、それ以外の場所だといいってことなのかね
探してみるね〜
@ES-Itoshima 
一昨年とか他に行きました…？多分コロナもあって結構制限とかもあった気はするんですが

**Comment by ES-Itoshima** [comment]
打ち上げ基本は百香えんやのみですね、、、、ただそれ以外の場所にするメリットがわからないです

**Comment by ES-hasuke** [comment]
飲みならやっぱりえんやになりますかね…一応他の飲み屋調べますね！

**Comment by ES-mabou** [comment]
@ES-Itoshima @ES-hasuke 
他のお店を見つけるのも大変そうですし、今回は演出さんには打ち上げのお店えんやで提案しときますね

**Comment by ES-hasuke** [comment]
ありがと〜
他のところも調べたけど、3Aから駅前に行く必要があったり、割と高めのところになっちゃうから、やっぱりえんやが1番行きやすそう！
それでお願いします🙇‍♀️
