### ISSUE TITLE
反省会日程調整・反省点募集フォーム作成

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#26]
私がとってもサボりまくってたので(カス)
今日中には作ります！！
@ES-Itoshima @ES-mabou @ESkoi-koi 
終わり次第投げるのでチェックお願いします🙏
日程調整の方は、明後日には全体に投げたいなというお気持ちです！

**Comment by ES-hasuke** [comment]
[反省会日程調整](https://forms.gle/WM1WjStVHY4MiEuW9)

[反省点募集](https://forms.gle/XQ8QjD6uJHzzerPRA)

@ESkoi-koi @ES-mabou @ES-Itoshima 
作成しました！チェックお願いします！
(補足)
多分卒公の練習がもう始まるので、対面でやるの難しそうだなと思って形式は全てオンラインにしてます…！

**Comment by ES-Itoshima** [comment]
@ES-hasuke 

もんだいないとおもいますい

**Comment by ES-hasuke** [comment]
チェックありがとうございます！じゃあ流しちゃいます！
