### ISSUE TITLE
集会願について

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#27]
@ES-mabou @ESkoi-koi 
3Aとか予約する時、大体紙の予約用紙が必要になるから、そろそろ馬籠先生にサインもらいにいくのがいいかな、と思ってるんやけど、うち2人にやり方教えたっけ…？
ちょっと来週くらいにどこかで教えたいから、日中空いてる時間帯教えて〜！(どっちか行けなくなった時のために、多分2人とも知っといた方が得なので)

**Comment by ES-mabou** [comment]
10/23 -15:00
10/24 -12:00,15:30-
10/25 12:00-
10/26 10:30-15:00
10/27 12:00-
10/28 -13:00
10/29 ‪✕‪

日中は~18:00くらいのつもりです

**Comment by ES-hasuke** [comment]
@ES-mabou @ESkoi-koi 
もし空いてたら、26日の4限の時間くらいにどうかしら！

**Comment by ES-hasuke** [comment]
@ES-mabou @ESkoi-koi 
ごめんこれ！！めっちゃ当日連絡になっちゃったけど、もし空いてたら14:00に中央図書館前集合で！10分くらいで終わると思う！
