### ISSUE TITLE
引き継ぎ建て込み教室予約

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#30]
@ES-mabou 
ごめん、めっちゃ失念してたけど、今引き継ぎ建て込みの教室予約の期間だから、なる早で3Aの教室いっぱい取った方がいい時期だった！
うち今日4限終わり空いてるから24、25の分取ってきちゃうね！

**Comment by ES-mabou** [comment]
わかりました！ありがとうございます！
