### ISSUE TITLE
引き継ぎ建て込み 機材借用

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#31]
引き継ぎ建て込みの借用機材が出揃ったので動き出しミで決めた担当で借用をしてきて欲しいです！
生活課:はーすけ、いとしま
実委:こいこい、いとしま
劇団系サークル:はーすけ、マー坊

↓2023年度卒公　借用機材
https://docs.google.com/spreadsheets/d/1tAXp09qkq1e-TC20XyqQRsAlH-bd-eF5g4k_LMajaf0/edit

**Comment by ES-hasuke** [comment]
[機材ドライブ](https://drive.google.com/drive/folders/1-U5vLDen8wN0Eai36M73gy70Ni_-Z-gI)
@ES-mabou 天才的に仕事が早くてお前が最強 
ありがと〜！
完了した時は、↑のドライブに書類アップロードするのとここのスレッドに報告って感じにしよっか！

@ES-Itoshima @ESkoi-koi もお願いします🙇
