### ISSUE TITLE
引き継ぎ建て込み 機材借用　実委

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#32]
実委ぶんの借用書作成ってお願いしてもいいですか？

**Comment by ESkoi-koi** [comment]
大変申し訳ございません！！！！至急作ります！

**Comment by ESkoi-koi** [comment]
[23卒公 実委 借用機材　引継ぎ建て込み.docx](https://github.com/ES-Itoshima/ES_producer/files/13267448/23.docx)

**Comment by ESkoi-koi** [comment]
一度作ってみたのですが貸出・返却日時の法則がつかめていないので間違っていると思われます…確認お願いします

**Comment by ES-Itoshima** [comment]
@ESkoi-koi ありがとう！！特に問題ないと思います！！
一応補足すると建て込み実験の前の日の１６時頃に借りて終わった日の次の日の午前に返す感じです！！
@ES-hasuke 一応チーフの確認お願いしてもいいですか？

**Comment by ES-hasuke** [comment]
確認しました！おっけーです！時間もまあ、16時半で大丈夫だと思います！
@ESkoi-koi @ES-Itoshima  
雙峰祭関係でバタバタしてて疲れてたろうにありがとうございます…！
助かります👍

@ESkoi-koi 
さらにごめんね、

info@sohosai.com

↑にメールを送るのと、昨日上げてくれた資料をドライブに上げてもらうのをお願いしてもいいか…？

[ドライブのリンクはここだよ](https://drive.google.com/drive/folders/1t30BPpKqi-oGbxXsUUlfqFywHeLmFF-6)

**Comment by ES-hasuke** [comment]
@ESkoi-koi メールはこんな感じで送ってもらうといいと思います！
うちの情報を全部自分の情報に変えて、資料を添付してくれればおっけーです！送ったら報告お願いします🙇

学園祭実行委員
担当者様
初めてご連絡させていただきます、
筑波大学ミュージカル集団ESSASSA
制作1年の西村晴菜と申します。
 
ESSASSAはこの度、卒業公演の引き継ぎ建て込みを行います。
その際、学園祭実行委員様の機材を借用したいと考えております。
詳細は添付した借用書をご覧ください。
 
よろしくお願いいたします。
 
筑波大学　情報学群　知識情報・図書館学類1年
学籍番号　202210015
西村晴菜
s2210015@s.tsukuba.ac.jp

**Comment by ESkoi-koi** [comment]
ドライブへのファイルの追加、また実委さんへのメールの送信完了しました。
お返事が来たらまた報告します！

**Comment by ES-hasuke** [comment]
3150(最高)
ありがとう🙏

**Comment by ESkoi-koi** [comment]
実委さんからお返事頂きまして、無事申請通りました！
当日中央図書館下倉庫にて貸し出しを行うとのことです！

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
最強 ありがと LOVE Chu
