### ISSUE TITLE
引き継ぎ建て込み機材借りについて

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#33]
@ES-Itoshima 
引き継ぎ建て込みの時、機材借りの指示出しをマー坊にお願いする予定なのですが、なんと当日親がアパートに来る関係でもしかすると私が来られないかもしれないことが発覚したので、ちょっと指示出しのサポートをお願いしてもいいですか…？
(来る時間ずれて行けそうなら行きます)

**Comment by ES-Itoshima** [comment]
了解
