### ISSUE TITLE
劇団系サークルの機材借用

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#34]
@ES-mabou  
[劇団系引き継ぎ建て込みフォルダ](https://drive.google.com/drive/folders/1Ll_sNME-H5jDnVnWloXsvmi8e-Kyi4eO)
この中に、卒公用の借用書入れた！
ただ、まだ記入はしてない(つくしょうさんのやつは春公のやつコピーして変更してない)ので、その部分の記入をお願いします🙇
借りる機材下に書いとくね↓

つくしょうさん
脚立 2
5mパイプ 2

NEUさん
Dotzパーライト 3個
3.4mスタンド 2本

10/30までに作ったやつここに送ってね！って言ったらできる…？
もしわからなそうだったら、明日とか練習で集まった時についでに一緒にやっちゃってもいいと思う！

**Comment by ES-mabou** [comment]
@ES-hasuke 
のいさんの借用書の方、どうやったら編集できるかわからないです

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/f4e1e458-1d4c-46e0-ab39-469153c03206)
↑の感じで、下に「フォームに記入」ってところがあるから、そこをタップするとpdfに書けるようになります！
で、書けたら「保存」を押すと、多分書いたところがそのまま保存されるはず！(もし中断する場合は途中でもやっちゃった方が楽)
ただ、うちも時々うまく保存されない時があるから、その時は教えて🙇

**Comment by ES-hasuke** [comment]
@ES-mabou 
ごめん確認遅れてた！のいさんの資料確認できました！オッケーだと思う！
メール、もしまだだったら送っちゃうね〜！

**Comment by ES-mabou** [comment]
すいません🙇‍♀️まだ送ってません！

**Comment by ES-hasuke** [comment]
@ES-mabou 
↑送りました！
お返事きたらまた共有するね👍

**Comment by ES-mabou** [comment]
ありがとうございます！🙇‍♀️

**Comment by ES-hasuke** [comment]
@ES-mabou 
すまねえ〜完全に連絡が遅れてたんだけど、つくしょうさんの方もオッケーだと思うから、劇団系サークルのLINEグルに資料送って「よろしくお願いします！」的なことを言ってもらってもいいですか…？

**Comment by ES-hasuke** [comment]
(ただの褒め)
おめえは本当に仕事がはええな…ありがと…！
