### ISSUE TITLE
実委さんの機材借用について

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#35]
@ES-Itoshima @ESkoi-koi 
雙峰祭お疲れ様でした！
そして終わってすぐに確認申し訳ないのですが、実委さんの機材借用に関する連絡ってどうなってますか…？

**Comment by ES-Itoshima** [comment]
@ES-hasuke 該当ISSUEに借用書あるので確認お願いします！！！！すみません！！
