### ISSUE TITLE
関係者名簿

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#36]
そういえばどうなってるこれ

**Comment by ES-hasuke** [comment]
@ES-Itoshima ！！！！！！！！！！！！！！！
リマインドどころか私自身が完全に失念してました…！
むしろ今思い出させてくださってありがとうございます！
至急作ります！
@ES-mabou 作ったらここに投げるから、Slackで全体に「確認お願いします！」みたいな感じで投げてもらえると助かる！

**Comment by ES-hasuke** [comment]
@ES-Itoshima ただあれじゃないですかね、オーディションの結果によって関わり方が変わる人もいるかと思うので、実はキャスト決まるまで作成できない説ありませんか？

**Comment by ES-Itoshima** [comment]
@ES-hasuke あごめんそういえば演出が作ることになったこと忘れてた
演出フォルダにあるので拾ってきてもらって役職名簿だけマー坊にたのんでつくってもらうのがいいかも

**Comment by ES-mabou** [comment]
すみません✋
関係者名簿は分かるんですけど、役職名簿ってなんですか？

**Comment by ES-hasuke** [comment]
関係者名簿は、キャストとかの関わり方を学年別に書いたやつで、役職名簿は役職ごとに分けたものって考えるとわかりやすいと思う！
大体、関係者名簿と同じスプシで別のページに作る場合が多いかな
春公でいうとこれ↓
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/60d50286-b81c-4971-a8b9-ac3446c96ecf)

**Comment by ES-mabou** [comment]
なるほど🤔
ありがとうございます！やってみます！

**Comment by ES-Itoshima** [comment]
ごめん確認遅くなってすごい今更なんだけど春公とかの関係者名簿に役職名入れると構成してる人々が返ってくる関数組んであるから今度からよければ使ってね

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
最強ニキ、ありがとうございます🙏
