### ISSUE TITLE
スケジュールと予算の提出

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#38]
@ES-mabou 
お疲れ様！スケジュールと予算は制作も提出する必要があるから、ちょっと早めに連絡しました！
スケジュールは、制作内動き出しミのものを出しちゃって、後から追加あれば追加する形がいいんじゃないかしらと思ってます！
で、予算がちょっと考えなきゃいけないところなんだけど、
一応毎回この項目出してるよってやつを、チーフのお仕事マニュアルに載せてあるのでここに載っけとくね↓
今回は入試とかで学内の教室使えない時が多くなっちゃうと思うから、その分外部予約がだいぶ多くなっちゃうかも？と思ってるんやけど、この項目をもとに自分で考えてもらうことってできたりする…？
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/51bb0985-7af6-40f0-8b55-a8147fb04291)

**Comment by ES-mabou** [comment]
ありがとうございます！
予算案出たら1度こっちに上げて確認させていただきます

**Comment by ES-mabou** [comment]
【制作】
11/17：スケジュール収集締め切り
12/5：予算収集締め切り
12/5：建て込み借用機材収集締め切り
11/19-11/21：(第1希望)建て込み機材借用
11/26-11/28：(第2希望)建て込み機材借用
12/2-12/4：(第3希望)建て込み機材借用
12/19-12/21：(第1希望)建て込み教室予約
12/26-12/27,1/5：(第2希望)建て込み教室予約
1/5：(第3希望)建て込み教室予約
1/5-1/12：(第1希望)本番機材借用
1/6-1/12：(第2希望)本番機材借用
1/13-1/20：(第3希望)本番機材借用
1/29-2/3：(第1希望)本番教室予約
2/6-2/10：(第2希望)本番教室予約
2/13-2/17：(第3希望)本番教室予約
2/14-2/20：(第1希望) 反省会・打ち上げ日程調整
2/21-2/27：(第2希望) 反省会・打ち上げ日程調整
2/28-3/6：(第3希望) 反省会・打ち上げ日程調整
3/4-3/10：(第1希望)反省会・打ち上げ
3/11-3/17：(第2希望) 反省会・打ち上げ
3/18-3/24：(第3希望) 反省会・打ち上げ

制作スケジュール(仮)です！
確認お願いします🙇‍♀️

**Comment by ES-hasuke** [comment]
ありがと！良いと思う！
あ！めっちゃ忘れてたけど、反省会の日程を入れとくといいかも…！
公演終わってから1週間以内にやることが多いかな

**Comment by ES-mabou** [comment]
修正しました！どうでしょうか…？

**Comment by ES-hasuke** [comment]
ありがと〜！大丈夫！
提出お願いします🙇

**Comment by ES-hasuke** [comment]
@ES-mabou 
まだ1週間あるけど一応リマインド！
予算考えれたらスレッドに投げてください！
一応何を出すか上に載せてはあるけど、わかんない項目あったら、直接とかSlackとかでもいいから相談してね！

**Comment by ES-mabou** [comment]
@ES-hasuke 
新しくissue作ってそっちに上げちゃいました

↓23卒公_制作予算
https://github.com/ES-Itoshima/ES_producer/issues/46
