### ISSUE TITLE
糸島教室予約＃１

### ISSUE THREAD

**Issue by ES-Itoshima** [ES-Itoshima/ES_producer#4]
9/1　午前中

必要人員：糸島

必要物品：予約票

作業工程

教室予約
スプシ編集
スプシor予約表提出

**Comment by ES-Itoshima** [comment]
スプシ、スレッドあげました確認お願いします
あと、教室予約って9月分だけで終わりで10月分いらないですよね？

**Comment by ES-Itoshima** [comment]
@ES-hasuke

**Comment by ES-hasuke** [comment]
あ、先ほどご説明したのですが念のため書いておきます！
10月は、プレゼン資料によれば有志のために教室を取ることはしないとは書いてあったのですが、全体曲の確認が土曜日にあって、通しが隔週で日曜日にあります！
その関係で、
10/7，10/14、10/15、10/21、10/28、10/29
は、本番と同じ教室(5C616,617)を確保してほしい、というご要望を頂いています！
演出さんに確認はしますが、いつもの練習用教室くらいは取っておくと、有志の人たちが「練習場所ないじゃん！」とならずに済むかなと思います…！
@ES-mabou @ESkoi-koi  も把握しといて欲しいので一応メンションしとくね
