### ISSUE TITLE
卒公スケジュール反映

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#40]
@ES-mabou 
スケジュール収集ありがとう！感謝！
(宣言)爆速で明日中にGoogleカレンダーに反映します！

**Comment by ES-hasuke** [comment]
@ES-mabou @ESkoi-koi @ES-Itoshima 
[Googleカレンダーダヨ](https://calendar.google.com/calendar/embed?src=hsb8k2k1ccqof6m737n41n6ao4%40group.calendar.google.com&ctz=Asia%2FTokyo)

スケジュール反映終わったｱｱｱｱｱ！！！！！！！！！！
深夜テンションですみません。確認お願いします！
@ES-mabou 
OKそうだったらチーフチャンネルに投げちゃってください🙇

**Comment by ES-mabou** [comment]
確認しました！仕事が早い…！
ありがとうございます🙇‍♀️
