### ISSUE TITLE
第三回三役ミ議事録

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#45]
@ES-mabou @ES-Itoshima 
前回、議事録を直前まで作れていない状態でミーティングしてしまったこともあって、かなりダラダラしてしまったところがあるかな、と思ったので、作成した上で制作としての見解を一応書きました！確認お願いします！もし制作の見解などについて間違ってるところがあれば当日までに直します！
(マー坊へ 良さげだったら三役に共有しちゃって、演出さんとか舞監さんにも自分たちの考えを書いてもらえるようにしちゃお)
[第三回三役ミ議事録](https://docs.google.com/document/d/1GnK5gdCHfAf9OHJ-OGlRfsigWxU1q5Me_dzKGbhX0D4/edit)

**Comment by ES-mabou** [comment]
ありがとうございます！そこまで気が回らなかった…
先生方との交渉が難しい以上、書いてあるとおりのことが現実的なように思いますね…
支援室との話し合い次第で先生方との交渉(それこそ支援室を間に挟んだりして)の余地あり？っていう希望的観測もあるっちゃあるかもです。

それはそれとして、とりあえずこの議事録は3役ミの方に投げときます

**Comment by ES-hasuke** [comment]
ありがとう！助かります🙏
音出しの交渉はね…
物理的には連絡が取れれば応じてはくれるようになってるかもしれんけどちょっと怖いかな、
チキるなという話ではあるし、うちとかの個人なら悪く思われちゃってもまだいいんだけど、
えっさ自体が学業を阻害するやべえ団体だと思われちゃう可能性があって(一応去年の卒でもその意見は出た)
そうなるとこの公演が良くても今後の活動がもっとやりにくくなっちゃうかもだからね…

**Comment by ES-mabou** [comment]
なるほど…
ありがとうございます
