### ISSUE TITLE
生活課　建て込み　借用機材

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#49]
@ES-Itoshima 
お疲れ様です！
生活課の借用機材が、おそらく今日中には確定するはずなので、明日以降に借りに行きましょう！
というか、一応私が木曜4限までなら空いているので、そこで借りてきちゃいます！

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/3855352f-52e9-41db-8d99-d0fe0c080766)
@ES-Itoshima 
一応、こんな感じで予約してきました！確認お願いします🙇
が、確認が遅れてて舞監さんの機材が足されることが今判明したので、また後日行ってきます！

**Comment by ES-Itoshima** [comment]
ぎゃあごめんなさいちょっと忙しくて見てなかったですありがとう、、、

**Comment by ESkoi-koi** [comment]
すみません照明チーフも兼ねているこいこいです…
照明の方で建て込み借用機材を確認してたところ500wスポットライト×1加え忘れておりましたすみません🙇‍♀️
今から新しく予約していただくことは可能ですか？ 
@ES-Itoshima @ES-hasuke

**Comment by ES-hasuke** [comment]
行ける！ただ、ちょっと火曜に授業入っちゃってるから、うちが行けるのは最速でも水曜かな？そこでよければ行ってくる！

@ES-Itoshima 
火曜に↑の変更行けたりしますか？もしできるならお願いしたいのですが…

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/cd676170-2f06-4313-9f3b-921c9dfa3229)![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/fc4728e8-d521-4464-acf0-dff55d4e6c21)
@ES-Itoshima @ESkoi-koi 
すみません、先週の水曜日とかいう大嘘ついたんですが、↑のやつと、あと舞監さんからリヤカーの追加あったの忘れてたので、今日建て込みの機材修正してきました！
これで大丈夫だとは思ってるのですが、一応確認お願いします🙇
