### ISSUE TITLE
23卒 スペサン

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#50]
@ES-hasuke 
卒公のパンフレットに載せるスペサンについて、以下の感じで提出しようと思います。
確認お願いします！

・劇団筑波小劇場
・人形劇団NEU
・筑波大学システム情報エリア支援室学生支援
・筑波大学生命環境エリア支援室学生支援
・筑波大学体育芸術エリア支援室学生支援
・筑波大学図書館情報エリア支援室学生支援
・筑波大学学生生活課
・筑波大学学園祭実行委員会
・つくば市竹園交流センター

今後の外部予約や車のレンタル次第で追加あり↓
(・つくば市春日交流センター)
(・つくば市桜交流センター)
(・ニコニコレンタカーつくは春日2丁目店)
(・カーシェア･つくば)

**Comment by ES-hasuke** [comment]
ありがと〜！
多分そんな感じで大丈夫だと思う！
交流センターはまだ本予約行ってないけどほぼ確実に使うから足しちゃってもいいかも！

**Comment by ES-mabou** [comment]
わかりました！ありがとうございます！
