### ISSUE TITLE
来年度本体会計予算について

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#51]
@ES-hasuke 
来年度の本体会計の予算について、制作が例年提出しているものってありますか？

**Comment by ES-hasuke** [comment]
ありがと〜！公演予算も出してくれてありがとね〜
多分、去年の本体会計資料を見た感じ、役職から提出するのは通年で使う用具を買い足したいとかそういうやつな気がするから、制作からは特にないかも？

ただガチなことをいうと今年の年始にまだ制作に入りたてだったからちょっとわかってないところもある気がする…

**Comment by ES-mabou** [comment]
ありがとうございます！
昨年の議事録見ればいいじゃんってメッセージ送信してから気づきました…
少しは自分で考えろという話

**Comment by ES-hasuke** [comment]
いやいや、確認は大事よ！ありがとう🙏
てかうちも今気づいてメッセージ編集したけど、いとしま先輩に聞かずとも遡って何年か分の資料見ればいいってことに気づいたわ
多分3年分くらい見たけどないから、大丈夫だと思う！

**Comment by ES-mabou** [comment]
ありがとうございます！
