### ISSUE TITLE
大学院入試期間中の交流センター予約

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#52]
@ES-mabou @ES-Itoshima @ESkoi-koi 
お疲れ様です！
すっっかり忘れてたんですが、大学院入試期間中の交流センター予約がそろそろ必要なんじゃないかなと思ったので、どこも使えない1/24〜26について(27以降は7Aが使えたはず)
今日春日交流センターに行って取れる分があればとってきます！
が、練習場所が空いていない可能性が当然あるので、新年にどなたかに行ってきていただけるとものすごくありがたいです…
私が8の昼頃に帰ってくるのですが、そこ以降だとちょっとギリギリすぎるかも…？と思っているので…

**Comment by ES-mabou** [comment]
そうだった…！
自分は7日の午後に帰ってくるので、8日の午前中に取りに行けます！

**Comment by ES-hasuke** [comment]
24が休息日なので、とりあえず25の18:00〜21:00で春日交流センター大会議室を押さえました！(まだ仮予約ですが)
ただ、取りたい時間が変わる可能性もあるため、ちょっと演出さんにも聞いてみます！

**Comment by ES-hasuke** [comment]
@ES-mabou 
一旦春日交流センターを25日に3時間確保しちゃったから、週に5時間っていうルール上26は2時間しか取れないことになっちゃうかも…？
ただ、5日前になると、空いてるところが全部取れるようになるから、とりあえずそうだな、
もし空いてたら18:00〜20:00までで春日交流センターを確保してもらっていいか…？
で、まあ20:00〜21:00の1時間だけ取る団体はそうそういないと思うから、5日前になった時にもう1時間取りに行く、って感じかな…？(伝わる？)
あと、年末で超忘れてたんだけど、1/27以降の7Aも確保してもらった方がいいかも！できたらお願いします🙇

**Comment by ES-mabou** [comment]
なるほど、5日前からなら時間制限なしに取れるようになるんですね。了解しました！
つくばに戻り次第交流センターと7Aの予約に行きます！

**Comment by ES-hasuke** [comment]
ありがと！！！

**Comment by ES-hasuke** [comment]
@ES-mabou 
教室予約報告の方にも今から言うんやけど、↑の1/25
18:00〜21:00と1/26の18:00〜20:00、とりあえず本予約してきました！
あとは、1/22以降に予約時間の制限なくなるから、そのタイミングでもう1時間本予約してくるね！

**Comment by ES-mabou** [comment]
ありがとうございます！
仮予約の書類はまだ私がもってるのですが、なくても本予約ってできるんですね
