### ISSUE TITLE
建て込み 機材借りについて

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#54]
@ES-hasuke 
建て込みの機材借りについて、引き継ぎ建て込みの際は60分でメニューを提出しましたが、建て込み実験でも同じ時間で提出していいのでしょうか
それとももう少し長めに取った方がいいでしょうか

**Comment by ES-hasuke** [comment]
ごめん全然気づいてなかった！ありがとう🙏
そうだな、機材借りの時は割と人が集まってくれるはず、だし、いままでも多分60分以内には終わってたはずなんだよな…だから多分60分で大丈夫だと思う！建て込みで時間足りない！ってなったら本番で変えよう！

**Comment by ES-mabou** [comment]
わかりました！ありがとうございます！
