### ISSUE TITLE
1/28 7A通し  運び出し＆車出し募集

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#55]
@ES-hasuke 
来週1/28に7Aで行う通しの件で運び出し機材と車出しの募集をしようと思うのですが、募集の締切について春公ではどうしていたとかの目安ってあるでしょうか？カーシェアのよやくの如何で決まるような気もしますが…

@ES-Itoshima 
カーシェアの予約って何日前までくらいなら大丈夫でしょうか？こちらも過去公演ではどうだったのような目安とかあれば助かります

**Comment by ES-hasuke** [comment]
機材と車出し募集は締め切り揃えてた覚えがあって、
どちらも1週間前までには連絡ください！にしてたはず！
そっから、前日までにはどこに何時集合でお願いします、みたいな調整をした上で連絡を流してた感じかな？

**Comment by ES-mabou** [comment]
@ES-hasuke 
どこに何時集合っていうのは、車を出してくれる方に、機材の積み込みのために車に来て欲しい時間と場所を共有するということでしょうか？
