### ISSUE TITLE
本番機材借用

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#56]
一応本番の借用機材について、提出が出揃ったので各担当は機材の確保に動き出してください！
↓卒公借用機材 スプシ
https://docs.google.com/spreadsheets/d/1tAXp09qkq1e-TC20XyqQRsAlH-bd-eF5g4k_LMajaf0/edit

予約が出来たら、こちらに書類のデータを提出してください！
↓googleドライブ 機材関連
https://drive.google.com/drive/folders/1-U5vLDen8wN0Eai36M73gy70Ni_-Z-gI

なお、後日借用機材について変更があるのは
舞監→建て込み後に暗幕を追加
音響→建て込み後に機材を減らす可能性あり
舞美→2/18にパイプの数確定
です！
変更があり次第こちらでも連絡します！

**Comment by ES-hasuke** [comment]
一応報告！
生活課、天才なので建て込みの機材修正ついでに取ってきました！確認お願いします🙇

**Comment by ES-mabou** [comment]
@ES-Itoshima @ESkoi-koi @ES-hasuke 
お疲れ様です！
そろそろ本番の機材借用が本格的に開始するので、各担当は動き出してください！借用時の書類はドライブに貼ってください！↓

https://drive.google.com/drive/folders/1-U5vLDen8wN0Eai36M73gy70Ni_-Z-gI

また3/11,12が後期入試でカンシタを使えないので、各機材の返却日程は3/13でお願いします！

**Comment by ES-mabou** [comment]
@ESkoi-koi 
舞監から、本番の実委暗幕は建て込み同様大を11枚、小を2枚借用して欲しいと連絡がありました！
実委に借用依頼を出す機材は建て込みと変わらない内容になりそうです。借用の手続きよろしくお願いします🙏

**Comment by ES-mabou** [comment]
@ES-hasuke 
お疲れ様です！建て込み後の借用機材の変更として、音響さんから生活課の16chミキサーの借用の取り下げの連絡がありました！
生活課の方で借用機材の修正をお願いします！あと、現在借用期間が3/6-3/11となっていると思うのですが、3/11,12は機材の返却が出来ないと思うので3/13に延長して欲しいです！

**Comment by ESkoi-koi** [comment]
実委さんの借用書です！確認をお願いします！
https://docs.google.com/document/d/e/2PACX-1vQuKcVLzEVEhZEjGzOKi3qgPBQnuHipSlGkNeE3a6uGrizI95kQtCt3TzSaS2JyWQ/pub

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
ごめん確認遅れた！大丈夫です！出しちゃってください！

@ES-mabou あと、生活課について一個報告！
3/11の午前中まで(11:45まで)だったら返せるよ、とのお話を生活課の方からはこの間いただいたんだけど、一応3/13に変更した方がいい？前行った時はその話聞いて
3/11でいいか、と思って帰ってきちゃったから、もしあれだったら今日練習後に変更してきます！
てかそもそも入試となるとカンシタの鍵が開かない感じ…か…？
他のところって3/13準拠にしてくれてるんだよね…？

**Comment by ES-mabou** [comment]
@ES-hasuke 
そうですね…
入試真っ只中だから多分警備員さんのカンシタ開ける判定厳しくなってると思いますし、3/13で統一しちゃいたいです！

**Comment by ES-hasuke** [comment]
ありがとう！
3/13に変更してきました！

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
ごめん！実委さんの借用書大丈夫なので、もしまだ出してなかったら出しちゃってください！

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
第一希望の実委さんの書類、大丈夫そう…？

**Comment by ES-hasuke** [comment]
@ES-mabou @ESkoi-koi @ES-Itoshima 
あと、私がバカすぎて演出さんに言われて気づいたんですが、万が一の時に公演が第二希望になる可能性もまだ、ゼロではない、ので、教室とか機材は確保しておかないとだよね、というお話をいただきました…！
公演が無事打てそうだったら取り消せばいい話なので、一応、同じ内容で日付だけ変えた書類を各所に送っていただいてもいいですか…？
生活課は私の方で今日の練習終わりに行ってくるので…！

**Comment by ES-mabou** [comment]
@ES-hasuke 
演出と舞監と相談して、本番の機材借りは3/5の練習前13:15からにしようということになりました
そのため実委さんの方に、機材を借りる時間を13:40くらいからにしてもらうことってできますか？

それとノイさんの機材を借りる件ですが、春日課外活動施設に3/6の9:00から用意してもらえることになりました(施設が開くのが9:00からなので)
今日7Aを見てきた感じどこに春日課外活動施設があるか分からなかったのですが、場所とかって把握できてたりしますかね？

**Comment by ES-hasuke** [comment]
おけ！ありがとう🙏
実委さんには今連絡中です！

春日課外活動施設、場所まだよくわかってないのよね…
ちょっと明日舞美作業後とかに見てくるわ

**Comment by ES-mabou** [comment]
ありがとうございます！

**Comment by ES-mabou** [comment]
@ESkoi-koi 
一応確認なのですが、暗幕の件で実委さんから何かお返事はありましたか？
