### ISSUE TITLE
2/6-2/10 本番教室予約

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#59]
そろそろ本番教室の予約が始まるので、教室予約の振り分けをしたいです！
2/6(火),7(水),8(木),9(金),13(火)のうち、午前9時に3Aまで教室予約に行ける日をそれぞれスレッドに投げてください！

**Comment by ES-mabou** [comment]
2/6‪ ✕‬
2/7 ○
2/8 ‪✕‬
2/9 ×
2/13 ×
すみません！🙇‍♀️
絶望的に予定が合わなくて2/7しか行けそうにないです…

**Comment by ES-hasuke** [comment]
2/7、8、9,13ならいけます！火曜は基本的に1限入っちゃってるから無理だけど、13は授業終わってると思うから多分いけます、
8、9はレポートで死んだように眠ってる可能性があるからどなたか起こしてください🙏

**Comment by ES-mabou** [comment]
今日のミーティングで決まった教室予約の割り振りです

2/6　こいこい
2/7　マー坊
2/8　いとしま
2/9　こいこい
2/13　はーすけ

皆さんよろしくお願いします！

**Comment by ES-mabou** [comment]
本番教室予約明日からです！
@ESkoi-koi 
支援室が9時に空くので、朝イチに教室予約お願いします！🙏
それと一緒に普段の練習の教室予約もして欲しいです！
