### ISSUE TITLE
今日の機材借りについて

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#60]
お疲れ様です！
@ES-hasuke  
今日の機材借りについてですが、リヤカー(実委の取っ手が鉄のリヤカー×1, 生活課のリヤカー×2)やネット付き台車(実委)がどこに置いてあるのか＆勝手に持って行っていいのか教えて頂きたいです！
また、筑小さんの機材がどこにあるかも知りたいです！
こんな直前で聞いてしまう形になってすみません…🙇‍♀️

@ESkoi-koi 
実委機材の運び出し時間についてですが、16:00からということで大丈夫でしょうか？
建て込みのメニュー的には16:30からとなっているのですが…

**Comment by ES-hasuke** [comment]
@ES-mabou 
ありがとう！
生活課さんのリヤカーは、大体生活課の倉庫前の外に置いてあって、実委さんのリヤカーは、カンシタでいつも舞美作業してるところに置いてあるって感じです！
(なんかユニークな名前がついてるやつは大体実委さんの)
どっちも確か鍵を借りなきゃいけなかったはずだから、とりあえずまず生活課さんのリヤカーの鍵を借りておいて、えっさのリヤカーと合わせて２つで機材を運んで、その後に実委さんのやつ借りる感じ！

あとごめん、実委さんの書類に関しては多分うちのチェックミス…
生活課さんの機材借りる時間があるし、多分最初はそっちに全員割かないとだから、17:00くらいにしてもらった方がいいかもね、ちょっとうちからメールと電話で連絡してみるわ

**Comment by ES-hasuke** [comment]
@ES-mabou @ESkoi-koi 
とりあえず、実委さんに電話で連絡取って、担当の方に連絡していただけるとのことです！
だから多分17:00〜になると思う！

@ES-mabou 
念のため実委さんの連絡先送っとくから、何かあったらこれ使ってね↓あと、本当にどうしていいかわからなかったらSlackなり電話なりください！
筑波大学学園祭実行委員会
副委員長物品・総括担当　谷田部 恭介
E-mail:info@sohosai.com
電話:029-853-2899

ガチで確認の怠りすぎて2人とも本当にごめん…🙇‍♀️
