### ISSUE TITLE
つくしょうさんからの機材借用願について

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#62]
@ES-mabou @ESkoi-koi @ES-Itoshima 
つくしょうさんから以下のような借用願のメールがきていたのですが、よく見たら本番どん被りじゃないか？と思ったので確認お願いします…！
@ESkoi-koi @ES-Itoshima 
照明さん的に、えっさのステラと調光ユニット1個使えなくなるのやばいのでは？と思っているんですがいかがでしょう…？
貸出期間を短縮しますか…？

筑波大学ミュージカル集団ESSASSA　ご担当様

お世話になっております。
劇団筑波小劇場　卒業公演制作の中山と申します。

劇団筑波小劇場の卒業公演に向けて、貸出していただきたい物品があるため、連絡を差し上げました。

お貸ししていただきたい物品、期間と用途は下記の通りです。
物品：ステージライト1個、調光ユニット1個　
期間：2月27日16時から3月9日18時
用途：演劇の公演
借用書を本メールに添付しておきましたので、そちらの確認もお願いします。

貸出の可否のお返事をお待ちしております。
何卒宜しくお願い致します。
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/fdcc74b7-f40c-43ff-9fef-03fd0abe405f)

**Comment by ES-mabou** [comment]
筑小さんと公演期間被るの結構やばくないですか？借用依頼があった機材の件もそうですが、パイプやステラ、医ステとかはいつも筑小さんから借りているものですし、公演期間が被ったとしてパイプやステラ・医ステを貸してもらえるのか。また、パイプが貸して貰えなければ公演は打てないとして、パイプは貸せるけどステラ・医ステは貸せないよってなった時に、それら無しでも照明が成り立つのか知りたいです
@ES-Itoshima @ESkoi-koi 
そこら辺どうなんでしょう？

あと、実際の本番日程がいつで、調整できるかも問い合せた方がいいですかね？厳しそうなら本番を第2希望にずらすか否かの三役ミを開く必要もあると思いますし…。こういうのってチーフの役割でしょうか。今Slackの制作チャンネルの方でかぶき會さんからの機材借用も来てるので(こっちは本番前且つ筑小さんの機材との被りがないはず)、どちらかに私が対応、もう片方に他の人が対応という形を取れると助かります…！

**Comment by ES-hasuke** [comment]
ありがとう！
多分、卒の本番スケジュールに関しては前座長間で話し合われてるはずだから、さら先輩に確認したら、以下のような返答をもらいました！つくしょうさんのミス説があるから、とりあえず劇団系サークルのLINEの方に共有してつくしょうさんにお伝えします！
今、さら先輩にはつくしょうさんの公演期間がいつか聞いてます！

もしミスじゃなくてガチで被ってたら三役ミ案件だから、メールもえっさGmailの方に来てたしうちがつくしょうさんの方は対応するわね、
かぶき会の方の対応頼みます…！
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/26bd9495-cfef-4f15-a87c-d35a31225971)

**Comment by ES-mabou** [comment]
了解です！

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/460fbc75-7383-48f1-b09c-862107d45c63)
@ES-mabou 
今、劇団系の交渉グルで確認してるけど、一応さら先輩から
↑ということらしいです…！
そういえばこれがあったから三役ミして第二希望に変えたんだったよね…
とりあえず、つくしょうさんからグループに返事があるのを待とうか…！

**Comment by ES-hasuke** [comment]
お疲れ様です。連絡ありがとうございます🙇つくしょうの仕込み期間が４日までなので、終わり次第至急返せるように確認しておきます。確認取れましたら、新しい借用書送らせていただくので少々お待ちください

@ES-mabou @ESkoi-koi @ES-Itoshima 
多分みんな見られるんですけど、一応↑のような返信をつくしょうさんからいただいたので、多分大丈夫です！
めちゃくちゃ皆さんをヒヤッとさせてしまった気がする、すみません…🙇‍♀️

**Comment by ES-mabou** [comment]
ありがとうございます！
良かったぁ😭
めっちゃ焦りました💦
はーすけ先輩の対応早くて助かりました！

**Comment by ES-mabou** [comment]
@ES-hasuke 
お疲れ様です！テスト週間で忙しい中すみません…！
筑小さんから機材借用が来ていた件について、筑小側の制作と連絡を取りたいのですが、借用書が送られてきたメールのアドレスを教えて貰ってもいいですか？
