### ISSUE TITLE
2/25 スタミ 制作スケジュール

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#64]
お疲れ様です！
2/25のスタミがオンラインで役職内のスケジュール確認が出来ないので、確認したかったことをここで共有します

@ESkoi-koi ( @ES-hasuke  )
反省会の日程調整はどうなっているでしょうか
スケジュール上だと2/21-2/27となっているので、なる早で全体に共有して欲しいです

@ES-Itoshima @ESkoi-koi @ES-hasuke 
新歓の教室予約が始まりました
新歓Slackの方で新たに教室予約報告チャンネルを作ったので、予約次第そちらに記入をお願いします🙏
改めて

火 → 糸島、はーすけ
金 → マー坊、こいこい

上記が各曜日教室予約担当なので、皆さん教室予約よろしくお願いします🙇‍♀️

**Comment by ES-hasuke** [comment]
反省会！やべごめん！出します！
@ESkoi-koi 
日程調整の方、今うちがサッと作って出しちゃうね
こいこいこには、反省点募集フォームの作成をお願いしたいです！27日までに作ってくれたらありがたい！です！
https://docs.google.com/forms/d/1Vueuj8GtHNgMRha-tQ-i6WHbcm7I5kCRyzRqFiIR-S0/edit
これ、春公演のときのやつ！参考にしてね↑

**Comment by ES-hasuke** [comment]
@ESkoi-koi( @ES-mabou )

https://forms.gle/C93Z1mugNKGL6cfS9

反省会日程調整フォーム作りました！チェックお願いします🙇‍♀️

よければ明日の朝には出しちゃいます！

**Comment by ES-mabou** [comment]
@ES-hasuke @ESkoi-koi @ES-Itoshima 
すみません、新歓の教室予約についてここのissueの初めに

火 → マー坊、こいこい
金 → 糸島、はーすけ

と書きましたが、正確には

火 → 糸島、はーすけ
金 → マー坊、こいこい

でした。各曜日の教室予約よろしくお願いします。
