### ISSUE TITLE
制作 卒公反省会

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#67]
@ES-Itoshima @ESkoi-koi @ES-hasuke 
3/19に全体の反省会があるので、それまでに制作内の反省会をしたいです！
3/18までで皆さんの空いている日時を教えてください🙇‍♀️

**Comment by ES-hasuke** [comment]
15 12:00〜18:00
16 一日OK
17 〜17:00 22:30〜
18 一日OK

**Comment by ES-mabou** [comment]
15 12:00-21:30
16 練習以外
17 22:00-
18 -13:00,21:30-23:30

**Comment by ES-mabou** [comment]
@ESkoi-koi @ES-Itoshima 
制作内反省会は今のところ、
3/15(金) 14:00-16:00,16:30-18:30
3/16(土) 16:30-
3/17(日) 22:30-
3/18(月) -13:00,21:30-23:30
が候補です。

この中で空いている時間はありますか？

**Comment by ES-hasuke** [comment]
すまん、予定が結構入っちゃって
15 14:00〜16:00 16:30〜18:30
18 〜13:00 21:30〜23:30

になってしまいました…ほんまごめん…
もしうちが合わなかったら、反省点スレッド立ててもらえれば遺言として反省点残します…ばちぼこごめんよ…

**Comment by ESkoi-koi** [comment]
マー坊のコメントにある時間帯ならどこでも大丈夫です！

**Comment by ES-mabou** [comment]
@ES-hasuke @ESkoi-koi @ES-Itoshima 
制作反省会の日程ですが、全員の日程調整ご集まりました。回答ありがとうございました🙇‍♀️
その結果、今日か明日中ならできるということになりました！
今日いきなりというと準備をする時間も必要ですし、**明日3/17の22:30から**オンラインでやりたいです！
こちら議事録です！反省点など事前に書き込んで頂けると当日スムーズに進めらると思うので、思いついたらじゃんじゃん書いていってください！🙏

23卒公 制作反省会 議事録
https://docs.google.com/document/d/1236rPskd5ACmpKOluGFg8mVmD22RPK44tSUSt0xwvxY/edit

**Comment by ES-hasuke** [comment]
ごめんパソコンでぎっとはぶのログインに手間取ってるからちょっと入るの遅れるかも…！すまん！
(追記)
あ、全然余裕で間に合いました

**Comment by ES-mabou** [comment]
すみません🙇‍♀️私もちょっと今設定に手間取ってるので、40分からにさせてください

**Comment by ES-mabou** [comment]
@ESkoi-koi @ES-hasuke @ES-Itoshima 
こちらからお願いします！

Zoom ミーティングに参加する
https://us05web.zoom.us/j/82302401967?pwd=O9uEHdOZ3QVMraHjTYY9MVLfkqix0a.1

ミーティング ID： 823 0240 1967
パスコード： Bu2BR5

**Comment by ES-mabou** [comment]
続きここから入ってください。
https://us05web.zoom.us/j/87530485194?pwd=VvKcwWzpsdUjAtqbEl9MOI58bpg9us.1

**Comment by ES-mabou** [comment]
連続でMT立てんなってzoomから言われちゃったので、
@ES-hasuke 代わりに立ててもらっていいですか？

**Comment by ES-hasuke** [comment]
makaserori

**Comment by ES-hasuke** [comment]
Zoom ミーティングに参加する
https://us05web.zoom.us/j/7616918710?pwd=a1EwNU1IRkFTMHkyQythbDRMVitPdz09

ミーティング ID： 761 691 8710
パスコード： 3xi18F



kotiradesu
