### ISSUE TITLE
過去公演鑑賞会用のプロジェクター予約

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#71]
@ES-mabou @ESkoi-koi @ES-Itoshima 
過去公演鑑賞会、新歓本祭のために、生活課のプロジェクターを予約する必要があると思います！
期間としては、
4/4〜8(新歓本祭で使うから、多分入学式の日は支援室関係開かない気がする)
4/12〜15(去年の芸サ合同新歓で、過去公演流してた記憶あり)
4/19〜22(20日にあって土日挟む)
4/26〜30(27、28、29であるっぽい)
5/2〜7(ゴールデンウィーク)

で、もうどこも期間的には取れるので、できれば明日、早急に取りたい、特に本祭の分は他のサークルにもう取られててもおかしくないんですが、私がちょっと明日行けるかどうかわからないので、どなたかお任せしてもよかったりしますか…？
@ES-mabou 
一応確認だけど新歓本祭も多分プロジェクター使うよね…？

![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/f5a0f2ee-cdbd-4832-ad6f-c31c6438c09f)

**Comment by ES-mabou** [comment]
すみません、俺が気づくべきことでした…
ありがとうございます！🙇‍♀️🙇‍♀️
そうですね…
@ESkoi-koi 
できれば明日の教室予約の際に、一緒に取りに行ってもらってもいいですか？

**Comment by ESkoi-koi** [comment]
4/4〜8以外の期間は予約してきました！
あまりよくわかっていなかったのでプロジェクターとスクリーン(大)を一つずつ借用予約してきたのですが何か訂正があったらお願いします！
![image](https://github.com/ES-Itoshima/ES_producer/assets/142914981/5083fe4e-116d-4a8c-b4f6-e29ef0d012b6)![image](https://github.com/ES-Itoshima/ES_producer/assets/142914981/f4687218-4aa5-4b70-8a87-20aa1c0b9190)

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
ありがとう！
新歓本祭はもしかして使わない…？

**Comment by ES-mabou** [comment]
俺も別件で生活課の機材を確認に行ったんですけど、どうも新歓祭として、新歓委員に生活課の機材をほとんど抑えられちゃってるんですよ。
たぶん改めて新推委？から機材を借りる手続きをすることになると思います
そこら辺は新歓隊長も関わってくることなので、今日の新歓ミで新歓祭中の機材について確認しようと思います
