### ISSUE TITLE
卒公 全体反省会

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#73]
@ES-hasuke 
お疲れ様です！
今度の全体反省会では制作チーフの私が司会をすることになると思うのですが、zoomの開設を任せて良いでしょうか？
また、反省会の司会をするにあたってスムーズに会を進行するために意識するべきことはあるでしょうか？

**Comment by ES-hasuke** [comment]
いいよ〜任せな👍


意識することなあ…まあ春公やそうほうさいは完全にうちがノリでやってたところあるんだけど…

・すでに出てる意見はそんなに読まなくてもいい(長くなりすぎちゃうし、みんな飽きちゃう)
から、みんなに読む時間取らせてあげて、補足とか追加の反省点を出してもらう時間を長めに取るといいかも！反省点募集の時点で思いつかなかったものとか、他の人の意見見て初めて出る対策とかが意外とあったりするからね…

・とにかく、「補足や意見ありませんか？」みたいに聞いてあげて、反省点の出し漏れ、言いたいけど言えなかったこと、がないようにすることは大事かな…
実際その場で言わなかったことを後から別の場所とかで色々言われると誰もスッキリしないしね…

・あと、これは自分がやりやすい方法を選んでもらって大丈夫なんだけど、うちは春公とそうほうさいで、合図なく議事録にみんなから色々書かれると、「次どれを拾ったらいいんだろう」となって自分が処理しきれなくて大変だった記憶あるから、
「皆さんは挙手のリアクションをした上で(ここ大事、特にチャットの場合書いてる最中に気づかず次行っちゃうこともありえるから)発言orチャットに書いてください、議事録にまとめたものを書き込むのは担当の人間がやるので」みたいに言ってあげてもいいかな…と思った！

くらいかな…
制作チーフはあくまで司会だから、意見を言いやすくしてあげるみたいな気持ちでいたらいいのかもと思ってます！
まあこんだけ言ったけどそこまで身構えなくても大丈夫だし、もし進行中に困ったらこっそりSlackとか投げてくれたら対応するから言ってね👍
議事録書くのもよかったらやるで

**Comment by ES-hasuke** [comment]
@ES-mabou 
あと、一応あれから新しく回答で出てる分は議事録にまとめといた(同じ意見は一個にした)から確認お願いします！！！！

**Comment by ES-mabou** [comment]
ありがとうございます！助かります！
よろしければ議事録も書いて欲しいです🙏
