### ISSUE TITLE
クラハの開閉

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#76]
@ES-hasuke 
明日から何度かクラハで練習があるのですが、クラハで練習をする際に警備員さんに鍵の開け閉めをしてもらっていたと思います。その際、どのようにして警備員さんを呼べばいいでしょうか。

**Comment by ES-hasuke** [comment]
5Cのプールの横(ってわかる？)に警備員室があるから、行きはそこに寄ってクラハの鍵を借りる

帰りは、警備員室に電話すると閉めにきてくれる感じ！
でも、電話番号がどれかわかんなくなっちゃったから、ちょっと行きのタイミングであらかじめ聞いてもらってもいいかな…？

**Comment by ES-mabou** [comment]
了解です！ありがとうございます！
