### ISSUE TITLE
打ち上げ＆反省会日程調整

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#80]
お疲れ様です！
新歓公演の打ち上げと反省会の日程調整が4/5-4/11となっていますので、各担当はそれまでに日程調整のフォームを作って全体に投げてください！
それぞれの担当は

打ち上げ→こいこい(補佐：はすけ)
反省会→マー坊(補佐：いとしま)

となっています！
よろしくお願いします🙇‍♀️

**Comment by ES-hasuke** [comment]
@ESkoi-koi 
日程調整、勝手に作ったから確認お願いします！
とりあえず
・授業のある平日が多いから、19時から打ち上げにしておいたよ
・新歓イベントのある日は全部避けたよ

っていうのに気をつけて次の新歓の時は作れば大丈夫だと思います！
こいこいこには予約の方をお願いするワ
https://forms.gle/GYcfwMNhKdmRacdq

@ES-mabou 
新歓公演の直後(21:00〜)も一応選択肢としては入れておいたけど、プレ打ち上げの意向は今の所ないんだっけ…？

@ESkoi-koi @ES-mabou @ES-Itoshima 
あと、一応本入団ミ前までの日でできそうなところ(新歓イベントのある日と、ゴールデンウィークは除く)という感じにしているのですが、調整できる日数がそこまで多くないのと、日程によっては新歓終わりかけの時期になるので、それだったら本入団ミ以降に「新歓の打ち上げ」としてやった方が良くね？と思う気持ちもあり…
ただ、その時にはもうみんな新入生への役職説明とかで打ち上げしてる場合じゃないよねえ…という気持ちもあって、ちょっとどこの日程を取ればいいか迷ってます…
私の考えすぎですかね…？よかったらご意見ください…！

**Comment by ES-mabou** [comment]
@ES-hasuke 
投げてくださったリンクが見れない見たいです💦すみませんがもう1回リンク投げてもらうことは出来ますか？
プレ打ちは演出に確認取るので少しお待ちください
新歓の打ち上げは本入団ミまでにしたいですね…

**Comment by ES-hasuke** [comment]
ありがとう！まじか

[新歓公演打ち上げフォーム](https://forms.gle/EjsbYss2ve4NH91q7)

これで見れる…？

**Comment by ES-mabou** [comment]
見れました！ありがとうございます！

**Comment by ES-mabou** [comment]
@ES-hasuke 
プレ打ちの件ですが、演出からはしない方向舵と連絡がありました！
のでフォームはそんな感じで大丈夫です！

あと反省会について質問なのですが、新歓の反省会は公演後にするか、新歓期間以降(本入団ミ以降)にするかどちらにするべきでしょうか

新歓の反省会として考えるのであれば、新歓イベントが終わった本入団ミ以降がいい気もしますが…

**Comment by ES-mabou** [comment]
@ES-Itoshima @ES-hasuke 
去年や一昨年は反省会いつ頃にやってましたか？

**Comment by ES-hasuke** [comment]
うあ〜めっちゃ返信遅れててごめん

去年は、打ち上げと同じく公演終わってから1週間以内にやった！
新歓全体の反省会は隊長管轄だからまた別でやったよ！

普通に合わせるとミーティング長くなりそうだから、今年も分けて公演後すぐにやっちゃっていいと思います！
