### ISSUE TITLE
4/7 車出し

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#81]
@ES-Itoshima 
お疲れ様です！
4/7の車出しの件ですが、8:20にカンシタに着く→荷物乗せて5Cに行く感じで車予約してもらってもいいですか？
また、カンシタに返却するときはおそらく15:10くらいに5Cに着いてもらって荷物を乗せてカンシタに向かうことになると思うのですが、そちらは可能でしょうか？

**Comment by ES-Itoshima** [comment]
かしこまり!
