### ISSUE TITLE
(懺悔)生活課機材借用

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#83]
私が忘れないように打っとくんですが、第二希望の生活課機材をこいこいちゃんに借りてもらっていたことに甘んじて、第一希望分を借りてくるのをすっかり忘れるとかいう、先輩として最悪のムーブをかましました
明日の朝イチで生活課行ってきます
他団体にもし借りられてたらなんとかします、本当にすみません

**Comment by ES-hasuke** [comment]
![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/89beda3c-9d82-4b4a-bd9c-14cd1fa8b3e0)

@ES-mabou 
ごめん、うちの勘違いすぎるんだけどこいこいたそが2月に確保してくれておりました、お騒がせしました
制作人って最高　CANMAKE TOKYO
ただ、その後チーフさんからの機材提出あった関係でちょっと変更があったから、そこは変更して、ドライブにも上げました！確認お願いします

つくしょうさんのやつを出し終わってからでいいんだけど、念のため各団体に送った書類をチーフチャンネルに送って、
「確認なんですが追加とかないですか？大丈夫ですか？」って念押しをしてもらえたら超安心かもしれない…！
もし余裕あればお願いします🙇‍♀️

**Comment by ES-mabou** [comment]
了解です！ありがとうございます！
