### ISSUE TITLE
打ち上げ日程調整

### ISSUE THREAD

**Issue by ESkoi-koi** [ES-Itoshima/ES_producer#85]
フォーム確認しました！
大丈夫そうでしたらすぐにSlackに投げたいなと思うので、投稿文のチェックをお願いします！

お疲れ様です！制作のこいこいです！
新歓公演の打ち上げの日程調整をそろそろ行いたいと思いましたので、下のGoogle formから4/14まで回答を送信してください！
打ち上げはえんやで19時〜行われるのでその点留意した上での回答をお願いします🙏

**Comment by ES-hasuke** [comment]
ありがとう！
一つだけ！
一応日程として、本番後の21日21:00〜も入れちゃってるから、それもメッセージで言ってくれたらもっと親切かも！
それ以外はバッチリです👌
進めてくれてありがとね〜！！
