### ISSUE TITLE
4/13(土) 芸サ合同新歓_車出し

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#86]
完全に私が失念していた事なのですが、今回の芸サ合同新歓は5C407/408のクソデカ教室なため、スカスカで寂しい感じになるし機材や衣装を置きたいよねという話になっていました。
そのため、運搬の為に車を出せたらと思っています。
芸サ合同新歓は前日の18:30以降から教室の準備が可能なため、4/12(金)の18:00-21:00の間で運び込みをして、4/13(土)当日の新歓終了後の18:00-21:00で機材を返しに行く予定です！

12(金)の18:20にカンシタ着→5Cへ
13(土)の19:00に5C着→カンシタへ
くらいで車を出したいのですが、どちらか一方でも良いので車を出してくださいませんか？
一応芸サ合同新歓担当からは、車出し無理そうなら手運びで出せるものだけ運ぶと聞いています

**Comment by ES-mabou** [comment]
あと、4/13(土)は一応5C616,617,618を1日取ってある(芸サ合同新歓で使う教室の対象外だった)ので、もし今からでも4/14(日)の5C616,617,618のいずれかを取れそうなら新歓おわったあとに機材関係を全部そこの教室に置いておければ、4/14(日)の通し後にまとめて機材を返す感じにして、13の夜と14の午前の運搬を省略できるかもです

**Comment by ES-Itoshima** [comment]
12なら出ます

**Comment by ES-mabou** [comment]
@ES-Itoshima 
では
4/12(金) 18:20にカンシタ着→5Cへ

このように車を出して頂きたいです
よろしくお願いします🙇‍♀️

**Comment by ES-mabou** [comment]
@ES-Itoshima 
すみません
機材は当日に手運びをすることになったので、車は予約しなくて大丈夫です
コロコロ変わってしまってすみません🙇‍♀️
