### ISSUE TITLE
本番機材返し

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#87]
4/22の11:10-機材返しがあるのですが、授業の関係で私が行けないためどなたか代わりに指示出ししてくださいませんか？

**Comment by ES-hasuke** [comment]
行けま〜す

**Comment by ES-Itoshima** [comment]
ikimasu

**Comment by ES-hasuke** [comment]
@ES-Itoshima 
機材返しの時、多分NEUさんの機材を春日の課外活動施設に返す必要があるのですが、車って出していただけたりしますか…？

**Comment by ES-mabou** [comment]
はーすけ先輩の方に連絡が行ったんですね。
借用の際はカンシタで受け取る形でしょうか？

**Comment by ES-hasuke** [comment]
いや、連絡とかは特にないかな…？
卒公の時がそうだったからそうじゃね？と思って言った感じ！

**Comment by ES-hasuke** [comment]
準備できた連絡って多分マー坊の方にも来てないよね…？
一応Discordの方で確認するね

**Comment by ES-mabou** [comment]
来てないですね
ちょうど今discord開いてたんで、私が聞いてみますよ

**Comment by ES-hasuke** [comment]
arigato

**Comment by ES-mabou** [comment]
貸し出しも返却も春日みたいです
確認が遅れてしまってすみません…
@ES-hasuke 
とりあえず今日借りる分ですが、春日まで取りに行って頂くことはできますか？いつ頃に取りに行くかも分かれば教えて欲しいです

**Comment by ES-hasuke** [comment]
おっけ〜！
ただ、自分が行けるのが18時以降になってて、車借りたあと一旦車でカンシタに向かおうと思ってるから、早くても取りに行けるのが18時半、遅いと19時以降になるかな、と思ってます！
まじで仕込みミの時に気づくべきやったね…本当にごめん…

軽トラには積めないやつばっかりだよね…？
わんちゃんいとしま先輩に行ってもらった方が早かったりする？と思ったけれど…
自分が取りに行く場合、取りに行けるのは確実に18時15分以降にはなります！

**Comment by ES-hasuke** [comment]
@ES-mabou 
すまん、もしかしたらいとしま先輩が軽トラで行ってくれるかもしれなくて、その関係で行ける時間が割と早まりそうだったのと、舞監さん的に、運搬の時間に軽トラか乗用車が機材取りに行ってると(運搬にどちらかが使えない時間があると)結構時間のロスになりそう、ということで
NEUさんの方に割と無茶な連絡を勝手にしてしまいました…ということをここにお詫びしておきます…

まあ、もともと借用書での借用時間が今日の12時からになってたし、NEUさんの方も18日に用意して連絡します、
って言ってたから、直前まで用意してないのはちょっとだけ向こうの非でもあるのだけれどね…

こちらとしては、
・春日に借りに行くことも機材借りに折り込んでおく、乗用車の担当者が行けなさそうならそのことを舞台監督に伝える

・前日までにDiscordで「用意できました」の連絡がない場合、「大丈夫そうですか？」の追い連絡する

のを次からやるといいかも！連絡取ってくれてありがとね〜🙏
