### ISSUE TITLE
春公教室予約

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#88]
春公の練習教室予約の分担を決めます！
履修が組めた人はこちらに何曜日なら予約に行けるか投げてください！

**Comment by ES-mabou** [comment]
木曜日か金曜なら行けます！
5月以降なら火曜でも大丈夫です！

**Comment by ES-hasuke** [comment]
月・火・金なら午前中行けます！

**Comment by ES-Itoshima** [comment]
ちょっとラボが不定期で入りそうなのでしんどいです、、、

**Comment by ES-mabou** [comment]
@ESkoi-koi 
こいこいはどうでしょうか？

**Comment by ES-mabou** [comment]
@ES-hasuke 
とりあえず私が金曜に予約に行くので、はーすけ先輩は火曜日お願いします！

@ESkoi-koi 
行ける日が分かり次第、連絡ください！

**Comment by ES-mabou** [comment]
@ESkoi-koi 
教室予約は何曜日なら行けるでしょうか？
