### ISSUE TITLE
打ち上げ日程調整(結果)

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#89]
@ES-mabou @ESkoi-koi 
打ち上げの結果来ました！
なんか「一応…」と思って21日21:00〜入れたら面白いくらい揃ったので21日でいいんじゃないか？と思ってるんだけどいかが？
その次が23 19:00〜
です！

![image](https://github.com/ES-Itoshima/ES_producer/assets/142915088/f5a08861-4f18-40eb-befa-4c61b84a8543)

**Comment by ES-mabou** [comment]
自分もそれで大丈夫だと思います！
@ESkoi-koi @ES-hasuke 
お店の予約と、日時・参加者・1人あたりの金額を全体に共有するのをお願いします🙏

**Comment by ESkoi-koi** [comment]
Slackで打ち上げ日程確定した旨を上げました！

**Comment by ES-mabou** [comment]
お店の予約もしました![image](https://github.com/ES-Itoshima/ES_producer/assets/142915132/32aec6f7-dc13-45bd-bd2d-cad7f0a1a916)

**Comment by ES-hasuke** [comment]
2人ともあざまる
