### ISSUE TITLE
制作新歓公演反省会_日程調整

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#90]
制作内の反省会の日程調整をします！
4/27(月)までで空いている日時を答えてください🙇‍♀️

**Comment by ES-mabou** [comment]
24 18:30-
25 21:30-
26 12:00-17:30
27 -12:00,21:30-

**Comment by ES-hasuke** [comment]
24 21:30〜
27 21:30〜

ならいけます！少なくてごめん！

**Comment by ES-hasuke** [comment]
@ES-Itoshima @ESkoi-koi 
この調子だと明日しか選択肢ないけども、行けます？

**Comment by ES-mabou** [comment]
こいこいは厳しいという連絡頂きました！
糸島さんは今dmでコンタクト取ってるんですけど、ちょっと厳しいですかね…
この感じだと全体反省会の後かもしれないです

**Comment by ES-mabou** [comment]
糸島先輩が今日大丈夫そうなので、今日の21:30からにしようと思います！
こいこいは議事録の確認お願いします🙇‍♀️

**Comment by ES-hasuke** [comment]
ごめん、はすけ多分家着くのがちょっとギリになるので、ご飯食べながら参戦します！

**Comment by ES-mabou** [comment]
わかりました！
はーすけ先輩時間やばそうなら、22:00からにしますか。
人少なすぎても出る意見限られますし。

**Comment by ES-hasuke** [comment]
@ES-mabou 
あ、なんか今電車の時間調べたら割と早く家つけそうなので、21時半からで大丈夫！！！
お騒がせしました🙇‍♂️

**Comment by ES-mabou** [comment]
https://docs.google.com/document/d/1k6y0QUKdK_aLsuGGIg3LKlNhNqfm-vKvniGhKGFgKkg/edit

直前となりましたが、こちら議事録です！

**Comment by ES-mabou** [comment]
こちらからお願いします！

Zoom ミーティングに参加する
https://us05web.zoom.us/j/86529374063?pwd=tfVmGz1EbW3DaQFjQNrUhjiWzxvUDf.1

ミーティング ID： 865 2937 4063
パスコード： t4NJSW

**Comment by ES-mabou** [comment]
Zoom ミーティングに参加する
https://us05web.zoom.us/j/87596256640?pwd=kDeN5mdzVcjp6A6mM5eSfsalvDMVRt.1

ミーティング ID： 875 9625 6640
パスコード： K0dEPP

**Comment by ES-mabou** [comment]
@ES-hasuke 　zoom立て直したんですが、入れますか？
