### ISSUE TITLE
ニコニコレンタカーの連絡先変更

### ISSUE THREAD

**Issue by ES-hasuke** [ES-Itoshima/ES_producer#91]
@ES-mabou 
昨日バラシの最中に、ニコニコレンタカーの連絡先が一昨年から変更されてなかったから、卒業した方に連絡の電話が行ってしまった、ということが起こっちゃったらしく、連絡先を現団員のものに変える必要があるそうです！
チーフだし2年生だし、ということでマー坊の連絡先に変更するのが1番丸いかな、と思うんだけれど、
変更にあたって、

①ニコニコレンタカーさんに電話
電話番号 029-886-9014

②連絡先の変更にあたって、新しい名義を登録する必要があるか、今の連絡先の変更で対応できるか確認

③今の連絡先変更で行けそうだったら、マー坊の電話番号を登録して、以前の連絡先を削除してもらう(誰の連絡先か名前聞かれたら　かまやち　りょう　って伝えてくれればわかると思う)

④新しく名義の登録が必要そうだったら、
ミュージカル集団ESSASSA
責任者:山本悠生
連絡先:(マー坊の電話番号)
で新しく登録をして、以前の名義を削除してもらう

という感じで、ニコニコレンタカーさんへの連絡をお願いしてもいいか…？

新歓公演終わりたてでそこまで急ぎではないから、時間ある時に対応お願いします！わからないことがあったらうちかいとしま先輩に聞いてください🙇‍♀️

**Comment by ES-mabou** [comment]
@ES-hasuke 
どうもニコニコレンタカーさんの方では団体名義での登録はできなくて、個人単位でしか管理をしていないのでらららさんの連絡先に電話が行った理由がよく分からない状態なのですが、おそらく「ミュージカル集団ESSASSA」の名義で領収書を切ったため、レンタルした本人が電話に出られなかった時に以前同じ名義でレンタルした方に電話が言ったんじゃないかと思います。
対応として借りた本人への電話を徹底するというふうに言われました。
