### ISSUE TITLE
1年 教室予約やってみよう

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#96]
そろそろ @ES-Mocchi の初教室予約に行きたいです！
来週以降で皆さんが1限(と可能であれば2限も)が空いている日程をとりあえず金曜まで教えてください！

**Comment by ES-mabou** [comment]
24 ×
25 ○
26 ×
27 ×
28 ○
自分はこんな感じです！

**Comment by ES-hasuke** [comment]
マー坊と同じくになっちゃうんだけど、
25
28
なら空いてます！

**Comment by ES-Mocchi** [comment]
25
26
なら2限まで空いてます！

**Comment by ES-mabou** [comment]
@ES-Mocchi 
じゃあ7Aまで予約に行くから、6/25の朝8:40に平砂共用棟前集合でよろしく！

**Comment by ES-Mocchi** [comment]
了解です！お願いします(*´▽｀*)
