### ISSUE TITLE
7/7 通し 車出しについて

### ISSUE THREAD

**Issue by ES-mabou** [ES-Itoshima/ES_producer#97]
お疲れ様です！
7/7の通しに7Aまで機材を運搬することになるのですが、どなたか車を出してくださいませんか？
たぶん行きは8:30-9:30のいつかくらいで、帰りは18:00-19:00くらいだと思います。(曖昧ですみません🙇‍♀️💦)

**Comment by ES-hasuke** [comment]
@ES-mabou 
時間的には帰りなら出せる…！けど、ちょっと運転能力的に自信がないので任せたい…！です！本当にごめん🙇‍♀️

**Comment by ES-mabou** [comment]
@ES-hasuke 了解です！

@ES-Itoshima @ESkoi-koi 
どうでしょうか？
今のところ、朝は9:25にカンシタ着、夕方は18:20に7A着くらいになりそうです！
